function [fitresult, gof] = createFitInter(xs, zs)
%CREATEFIT(XS,ZS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xs
%      Y Output: zs
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-May-2017 17:48:14
% this is used to convert the xs-ys data into a uniform vector
% which can then be used to find the error incurred in analytical model

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xs, zs );

% Set up fittype and options.
ft = 'pchipinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'zs vs. xs', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel xs
ylabel zs
grid on
close
end
