function [fitresult, gof] = createFitHx(x, z)
%CREATEFIT(XS1,ZS1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xs1
%      Y Output: zs1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-May-2017 15:43:25
%% This fit has been used to get the regression model of first link characteristics


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, z );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'zs1 vs. xs1', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel X/d_j
ylabel Z/d_j
grid on
axis equal
camup([-1 0 0])
if ~exist('fitplots', 'dir')
mkdir('fitplots');
end
name = sprintf('fitplots/fit.png');
saveas(gcf,name);
close
end
